# ReadTheDocs configuration for Underworld3 API documentation
# Uses pixi for conda-forge PETSc environment
# See https://docs.readthedocs.com/platform/stable/build-customization.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    # Install pixi
    - curl -fsSL https://pixi.sh/install.sh | bash
    - export PATH="$HOME/.pixi/bin:$PATH"

    # Install the dev environment (includes Sphinx and PETSc)
    - pixi install -e dev

    # Build underworld3
    - pixi run -e dev build

    # Build Sphinx documentation
    - pixi run -e dev api-docs-build

    # Move output to ReadTheDocs expected location
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - cp -r docs/api/_build/html/* $READTHEDOCS_OUTPUT/html/
