"""Native tetrahedral single-edge bisection (uwnvb_bisect) — stage 1c-i.

Validates the DM_POLYTOPE_TETRAHEDRON production tables of the native
``uwnvb_bisect`` DMPlexTransform (generated by
``docs/developer/design/tet_bisection_tables_generator.py``): bisecting a
marked edge splits every tet in its star into two children plus an interior
triangle, with the faces containing the edge splitting via the triangle
single-split rule. Each case checks the full PETSc battery
(``-dm_plex_check_all``: symmetry, skeleton, face cones/orientations,
geometry/inversion), volume conservation, orientation class, and vertex-set
equality against the pure-python split.

The two-tet shared-face cases are the orientation-reconciliation tests: the
two cells see the shared face with different cone orientations, exercising
the D3 group composition in GetSubcellOrientation (whose former ``-(o+1)``
shortcut was wrong for rotated views — only reachable from 3D).
"""
import itertools

import numpy as np
import pytest
import underworld3  # noqa: F401  (PETSc init + build environment)
from petsc4py import PETSc

pytestmark = [pytest.mark.level_2, pytest.mark.tier_b]

_nvbx = pytest.importorskip(
    "underworld3.utilities._nvb_transform",
    reason="native uwnvb transform not built in this environment")

BISECT_LABEL = "uwnvb_bisect_edges"

REF = np.array([[-1.0, -1.0, -1.0], [-1.0, 1.0, -1.0],
                [1.0, -1.0, -1.0], [-1.0, -1.0, 1.0]])


def _make_dm(coords, cells):
    coords = np.asarray(coords, float)
    cells = np.asarray(cells, dtype=np.int32).copy()
    # DMPlex tet orientation class: det[v1-v0, v2-v0, v3-v0] < 0
    e = coords[cells[:, 1:]] - coords[cells[:, :1]]
    wrong = np.linalg.det(e) > 0
    cells[wrong, 2], cells[wrong, 3] = cells[wrong, 3], cells[wrong, 2].copy()
    return PETSc.DMPlex().createFromCellList(
        3, cells, coords, interpolate=True, comm=PETSc.COMM_SELF)


def _edge_point(dm, va, vb):
    vS, _ = dm.getDepthStratum(0)
    eS, eE = dm.getDepthStratum(1)
    want = frozenset((va, vb))
    for e in range(eS, eE):
        if frozenset(int(v - vS) for v in dm.getCone(e)) == want:
            return e
    raise KeyError((va, vb))


def _apply_bisect(dm, edge_pts):
    d = dm.clone()
    d.createLabel(BISECT_LABEL)
    lab = d.getLabel(BISECT_LABEL)
    for e in edge_pts:
        lab.setValue(e, 1)
    tr = PETSc.DMPlexTransform().create(comm=d.comm)
    tr.setType("uwnvb_bisect")
    tr.setDM(d)
    tr.setUp()
    out = tr.apply(d)
    tr.destroy()
    return out


def _check_all(dm):
    opts = PETSc.Options()
    opts["dm_plex_check_all"] = None
    dm.setFromOptions()
    del opts["dm_plex_check_all"]


def _cells_and_volumes(dm):
    vS, vE = dm.getDepthStratum(0)
    cS, cE = dm.getHeightStratum(0)
    coords = dm.getCoordinatesLocal().array.reshape(-1, 3)
    sets, vols = [], []
    for c in range(cS, cE):
        clos = dm.getTransitiveClosure(c)[0]
        vs = [coords[p - vS] for p in clos if vS <= p < vE]
        sets.append(frozenset(tuple(np.round(v, 12)) for v in vs))
        e = np.array([vs[i] - vs[0] for i in (1, 2, 3)])
        vols.append(np.linalg.det(e) / 6.0)
    return sets, np.array(vols)


def _reference_split(coords, cells, edge_pairs):
    """Star split of the marked edges by direct construction — the
    rule-independent vertex-set truth the transform must reproduce."""
    coords = [np.asarray(p, float) for p in coords]
    live = [tuple(c) for c in cells]
    for (va, vb) in edge_pairs:
        coords.append(0.5 * (coords[va] + coords[vb]))
        m = len(coords) - 1
        nxt = []
        for cell in live:
            if va in cell and vb in cell:
                others = [v for v in cell if v not in (va, vb)]
                nxt.append((va, m, *others))
                nxt.append((m, vb, *others))
            else:
                nxt.append(cell)
        live = nxt
    return [frozenset(tuple(np.round(coords[v], 12)) for v in cell)
            for cell in live]


def _run_case(coords, cells, edge_pairs):
    dm = _make_dm(coords, cells)
    _check_all(dm)
    out = _apply_bisect(dm, [_edge_point(dm, a, b) for a, b in edge_pairs])
    _check_all(out)
    _, v_in = _cells_and_volumes(dm)
    got, v_out = _cells_and_volumes(out)
    assert np.all(np.sign(v_out) == np.sign(v_in[0]))
    assert abs(v_out.sum() - v_in.sum()) < 1e-12
    want = _reference_split(coords, cells, edge_pairs)
    assert sorted(map(sorted, map(list, got))) == \
        sorted(map(sorted, map(list, want)))


def test_single_tet_all_six_edges():
    for pair in [(0, 1), (1, 2), (2, 0), (0, 3), (1, 3), (2, 3)]:
        _run_case(REF, [[0, 1, 2, 3]], [pair])


def test_two_tets_shared_face_reconciliation():
    coords = np.vstack([REF, [[1.0, 1.0, 1.0]]])
    cells = [[0, 1, 2, 3], [1, 2, 3, 4]]      # shared face {1,2,3}
    for pair in [(1, 2), (1, 3), (2, 3), (0, 1), (0, 3), (1, 4)]:
        _run_case(coords, cells, [pair])


def _kuhn(n=2):
    idx, coords = {}, []
    for i in range(n + 1):
        for j in range(n + 1):
            for k in range(n + 1):
                idx[(i, j, k)] = len(coords)
                coords.append(np.array([i, j, k], float) / n)
    cells = []
    for i in range(n):
        for j in range(n):
            for k in range(n):
                o = np.array([i, j, k])
                for perm in itertools.permutations(range(3)):
                    path = [o.copy()]
                    for p in perm:
                        q = path[-1].copy()
                        q[p] += 1
                        path.append(q)
                    cells.append(tuple(idx[tuple(q)] for q in path))
    return np.array(coords), cells


def test_native_driver_matches_serial_engine_multipass():
    """The native UWNVBRefine driver and the serial TaggedBisectionMesh
    engine share one seed (write_tagged_state_label runs the engine's own
    initialization), so multi-pass graded refinement driven by the same
    metric must produce the same mesh, cell for cell."""
    import underworld3 as uw
    from underworld3.utilities.nvb import (TaggedBisectionMesh,
                                           write_tagged_state_label)

    base = uw.meshing.UnstructuredSimplexBox(
        minCoords=(0, 0, 0), maxCoords=(1, 1, 1), cellSize=0.4,
        refinement=1, qdegree=2)
    dm0 = base.dm_hierarchy[-1]

    def target_h(centroids):
        r = np.linalg.norm(np.asarray(centroids) - 0.5, axis=1)
        return np.where(r < 0.2, 0.08, np.minimum(0.08 + (0.4 - 0.08)
                                                  * (r - 0.2) / 0.25, 0.4))

    # serial engine (from the raw base, before the native seed label is added)
    eng = TaggedBisectionMesh.from_dm(dm0)
    for _ in range(3):
        cen, h, cids = eng.centroids_h()
        sel = np.where(h > target_h(cen))[0]
        if sel.size == 0:
            break
        eng.refine(set(int(cids[j]) for j in sel))
    want = []
    coords_all = np.array(eng.coords)
    for verts, _ in eng.cells.values():
        want.append(frozenset(tuple(np.round(coords_all[v], 12))
                              for v in verts))

    # native driver, same seed, same marking rule
    write_tagged_state_label(dm0)
    current = dm0
    for _ in range(3):
        cs, ce = current.getHeightStratum(0)
        cen = np.empty((ce - cs, 3))
        h = np.empty(ce - cs)
        for i, c in enumerate(range(cs, ce)):
            vol, ccen = current.computeCellGeometryFVM(c)[0:2]
            cen[i] = np.asarray(ccen)[:3]
            h[i] = (6.0 * abs(float(vol))) ** (1.0 / 3.0)
        sel = np.where(h > target_h(cen))[0]
        if sel.size == 0:
            break
        d = current.clone()
        d.createLabel("adapt")
        lab = d.getLabel("adapt")
        for j in sel:
            lab.setValue(int(cs + j), 1)
        current = _nvbx.refine(d, "adapt")
    got, _ = _cells_and_volumes(current)

    assert sorted(map(sorted, map(list, got))) == \
        sorted(map(sorted, map(list, want)))


def test_kuhn_mesh_independent_edge_stars():
    coords, cells = _kuhn(2)
    dm = _make_dm(coords, cells)
    vS, _ = dm.getDepthStratum(0)
    eS, eE = dm.getDepthStratum(1)
    used, picked = set(), []
    for e in range(eS, eE):
        star = set()
        for f in dm.getSupport(e):
            star.update(int(c) for c in dm.getSupport(f))
        if star & used:
            continue
        picked.append(tuple(int(v - vS) for v in dm.getCone(e)))
        used |= star
        if len(picked) == 6:
            break
    _run_case(coords, cells, picked)
