#!/bin/bash -v


# echo
# echo Install uw3_env during postBuild phase
# echo

# conda env list

# # conda init
# # conda activate notebook
# # mamba install --yes -c jgiordani uw3_env

echo
echo Install jupyter extensions
echo

# install required python packages
python3 -m pip install "jupyter-server-proxy"
python3 -m pip install "jupyterlab-quarto>=0.3.3"
python3 -m pip install "jupytext>=1.16.1"
python3 -m pip install "trame_jupyter_extension"

# We install the local code "properly" - no point in a dev build here

echo
echo Install local UW3 
echo

# Note: we would be better to find a way to access this directly
# CONDA_PREFIX=`conda run -n notebook bash -c "echo \${CONDA_PREFIX}"`

export CONDA_PREFIX=/srv/conda/envs/notebook/
export PYTHONPATH=$CONDA_PREFIX/lib

# debugging if required
# python -c "import petsc4py; print(petsc4py.get_config())"
# python -c "from petsc4py import PETSc; print('Imported PETSc')"

# Build / install the uw3 in this repo

pip install .


echo
echo Completed
echo