#!/bin/bash -v


# echo
# echo Install uw3_env during postBuild phase
# echo

# conda env list

# # conda init
# # conda activate notebook
# # mamba install --yes -c jgiordani uw3_env

echo
echo Install jupyter extensions
echo

# install required python packages
python3 -m pip install "jupyter-server-proxy"
python3 -m pip install "jupyterlab-quarto>=0.3.3"
python3 -m pip install "jupytext>=1.16.1"
python3 -m pip install "trame_jupyter_extension"

# We install the local code "properly" - no point in a dev build here

echo
echo Check petsc / uw3_env
echo

# python3 setup.py develop
# python3 setup.py build_ext

echo Conda prefix:
echo $CONDA_PREFIX

conda run -n notebook PYTHONPATH=$CONDA_PREFIX/lib python -c "import petsc4py; print(petsc4py.get_config())"
conda run -n notebook PYTHONPATH=$CONDA_PREFIX/lib python -c "from petsc4py import PETSc"

python -c "import petsc4py; print(petsc4py.get_config())"
python -c "from petsc4py import PETSc"

export PYTHONPATH=$CONDA_PREFIX/lib

python -c "import petsc4py; print(petsc4py.get_config())"
python -c "from petsc4py import PETSc; print('Imported PETSc')"


echo
echo Install local UW3 pt 2
echo

conda run -n notebook PYTHONPATH=$CONDA_PREFIX/lib/ pip3 install .

echo
echo Completed
echo