name: Repo Support Bot

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]
  discussion:
    types: [created, edited]
  discussion_comment:
    types: [created]

jobs:
  reply:
    runs-on: ubuntu-latest
    steps:
      - name: Extract text
        uses: actions/github-script@v7
        id: extract
        with:
          script: |
            const p = context.payload;
            let text = "";
            if (p.issue && (p.action === "opened" || p.action === "edited")) {
              text = p.issue.body || "";
            } else if (p.comment && p.action === "created") {
              text = p.comment.body || "";
            } else if (p.discussion && (p.action === "created" || p.action === "edited")) {
              text = p.discussion.body || "";
            } else if (p.discussion_comment && p.action === "created") {
              text = p.discussion_comment.body || "";
            }
            return text;

      - name: Ask bot
        id: askbot
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.BOT_API_URL }}/ask
          method: "POST"
          customHeaders: |
            Content-Type: application/json
          data: |
            { "question": "${{ steps.extract.outputs.result }}", "max_context_items": 6 }

      - name: Post reply
        uses: actions/github-script@v7
        with:
          script: |
            const res = JSON.parse(`${{ steps.askbot.outputs.response }}`);
            const body = res.answer + "\n\nCitations:\n" + (res.citations || []).map(c=>`- ${c}`).join("\n");
            if (context.payload.comment) {
              await github.rest.issues.createComment({
                owner: context.repo.owner, repo: context.repo.repo,
                issue_number: context.payload.issue.number, body
              });
            } else if (context.payload.issue) {
              await github.rest.issues.createComment({
                owner: context.repo.owner, repo: context.repo.repo,
                issue_number: context.payload.issue.number, body
              });
            } else if (context.payload.discussion) {
              await github.rest.discussions.createComment({
                owner: context.repo.owner, repo: context.repo.repo,
                discussion_number: context.payload.discussion.number, body
              });
            } else if (context.payload.discussion_comment) {
              await github.rest.discussions.createComment({
                owner: context.repo.owner, repo: context.repo.repo,
                discussion_number: context.payload.discussion_comment.discussion_number, body
              });
            }
