# syntax=docker/dockerfile:1.7-labs

### how to build Underworld3 image
### MUST run from the underworld3 top directory
#    $ podman build ./docs/development -f ./Containerfile \
#        --rm --format docker  \
#        -t underworldcode/underworld3:version_id
### needs the --format tag to run on podman

FROM docker.io/mambaorg/micromamba:2.3.0

# create the env
COPY --chown=$MAMBA_USER:$MAMBA_USER environment.yml /tmp/env.yaml
RUN micromamba install -y -n base -f /tmp/env.yaml && \
    micromamba clean --all --yes

# activate mamba env during podman build
ARG MAMBA_DOCKERFILE_ACTIVATE=1

# install UW3
WORKDIR /tmp
COPY --exclude=**/.git \
     --chown=$MAMBA_USER:$MAMBA_USER \
     . /tmp/underworld3
WORKDIR /tmp/underworld3

RUN pip install --no-build-isolation --no-cache-dir .

# setup /uw_dir in container to run everything as the root user.
ENV UW_DIR=/uw_dir
COPY ./tests   $UW_DIR/tests
WORKDIR $UW_DIR

EXPOSE 8888

CMD ["jupyter-lab", "--no-browser", "--ip=0.0.0.0", "--allow-root", "--notebook-dir=$UW_DIR"]
